import { Product } from "./types";

export const products: Product[] = [
  {
    id: "prothio-250-ec",
    activeSubstance: "Prothioconazole",
    productName: "Prothio 250 EC",
    type: "Fungicide",
    projectOwner: "John Murphy",
    countries: ["IE", "UK", "DE", "FR", "PL"],
    submissionType: "Renewal",
    status: "Dossier preparation",
    targetSubmissionDate: "2026-06-15",
    dataResponsibility: "LS",
    euApprovalStatus: "Approved",
    euExpiryDate: "2027-04-30",
    assessments: [
      {
        sectionId: "aquatics",
        riskLevel: "pass-with-mitigation",
        summary:
          "Passes with 20m buffer zone (SPe3). Tier 1 TER for fish = 12.5 (trigger 100). FOCUS Step 3 refinement needed for Daphnia.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-01-15",
        details: {
          "TER Fish (Tier 1)": 12.5,
          "TER Daphnia (FOCUS Step 3)": 105,
          "Buffer Zone": "20m",
          "Mitigation": "SPe3 buffer zone required",
        },
      },
      {
        sectionId: "groundwater",
        riskLevel: "refinement-needed",
        summary:
          "Parent compound passes. Metabolite M700F007 exceeds 0.1 ug/L in 3/9 FOCUS scenarios. Lysimeter study ongoing.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-01-10",
      },
      {
        sectionId: "soil",
        riskLevel: "pass",
        summary: "All TER values above trigger. DT50 = 28 days. No accumulation concerns.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-01-12",
      },
      {
        sectionId: "bees",
        riskLevel: "pass",
        summary: "HQ oral = 0.02, HQ contact = 0.01. Well below triggers. No higher tier needed.",
        assessor: "Mark Daly",
        lastUpdated: "2025-12-20",
      },
      {
        sectionId: "birds-mammals",
        riskLevel: "pass-with-mitigation",
        summary:
          "Tier 1 fails for granivorous birds. PT assessment with refined focal species (skylark) passes. SPe5 statement needed.",
        assessor: "Mark Daly",
        lastUpdated: "2025-12-22",
      },
      {
        sectionId: "nta",
        riskLevel: "pass",
        summary: "In-field HQ = 0.8 (trigger 2). Off-field with drift reduction passes.",
        assessor: "Mark Daly",
        lastUpdated: "2025-12-18",
      },
      {
        sectionId: "ntp",
        riskLevel: "not-started",
        summary: "",
        assessor: "Mark Daly",
      },
      {
        sectionId: "operator",
        riskLevel: "pass",
        summary:
          "AOEL not exceeded with PPE. Operator exposure 45% AOEL with gloves during mixing/loading.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-05",
      },
      {
        sectionId: "worker",
        riskLevel: "pass",
        summary: "Re-entry interval of 48h sufficient. Worker exposure 28% AOEL.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-05",
      },
      {
        sectionId: "resident-bystander",
        riskLevel: "pass",
        summary: "Resident exposure 15% AOEL. Bystander 8% AOEL. No buffer required.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-06",
      },
      {
        sectionId: "classification",
        riskLevel: "pass-with-mitigation",
        summary: "Repr. 2 H361d classification. Product label must reflect classification.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-11-30",
      },
      {
        sectionId: "gw-metabolites",
        riskLevel: "refinement-needed",
        summary:
          "Metabolite prothioconazole-desthio classified as relevant. Monitoring data being compiled for 3 Member States.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-08",
      },
      {
        sectionId: "validation",
        riskLevel: "pass",
        summary:
          "ILV completed. Method validated for all matrices. LOQ meets requirements.",
        assessor: "Tom Brennan",
        lastUpdated: "2025-11-15",
      },
      {
        sectionId: "residue-studies",
        riskLevel: "pass-with-mitigation",
        summary:
          "8 Northern EU trials, 8 Southern EU trials completed. MRL proposal of 0.3 mg/kg for cereals.",
        assessor: "Anna Kowalski",
        lastUpdated: "2026-01-20",
      },
      {
        sectionId: "consumer-chronic",
        riskLevel: "pass",
        summary: "Chronic dietary intake 12% ADI (EFSA PRIMo rev.3). Well within acceptable limits.",
        assessor: "Anna Kowalski",
        lastUpdated: "2026-01-20",
      },
      {
        sectionId: "consumer-acute",
        riskLevel: "pass",
        summary: "Acute dietary intake 35% ARfD for cereals. Acceptable.",
        assessor: "Anna Kowalski",
        lastUpdated: "2026-01-20",
      },
      {
        sectionId: "combined-risk",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "field-trials",
        riskLevel: "pass",
        summary: "12 field trials across 4 Member States. Consistent efficacy >85% against target pathogens.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-10-30",
      },
      {
        sectionId: "bad",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "effectiveness",
        riskLevel: "pass",
        summary: "Demonstrates equivalent efficacy to reference product across all tested GAPs.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-11-01",
      },
      {
        sectionId: "resistance",
        riskLevel: "pass-with-mitigation",
        summary:
          "FRAC Group 3 (DMI). Resistance management strategy required. Max 2 applications per season recommended.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-11-01",
      },
    ],
  },
  {
    id: "prothio-metco",
    activeSubstance: "Prothioconazole",
    productName: "Prothio/Metco 100/48",
    type: "Fungicide",
    projectOwner: "John Murphy",
    countries: ["DE", "FR", "PL", "CZ"],
    submissionType: "Renewal",
    status: "Preliminary ERA ongoing",
    targetSubmissionDate: "2026-09-01",
    dataResponsibility: "LS",
    euApprovalStatus: "Approved",
    euExpiryDate: "2027-04-30",
    assessments: [
      {
        sectionId: "aquatics",
        riskLevel: "refinement-needed",
        summary: "Combination product - additive toxicity assessment required. Metconazole TER for fish below trigger at Tier 1.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-01-25",
      },
      {
        sectionId: "groundwater",
        riskLevel: "fail",
        summary: "Metconazole metabolite exceeds 0.1 ug/L in 7/9 FOCUS GW scenarios. No viable refinement path identified yet.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-01-25",
      },
      {
        sectionId: "soil",
        riskLevel: "pass",
        summary: "Both actives pass. Combined DT50 acceptable.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-01-20",
      },
      {
        sectionId: "bees",
        riskLevel: "pass",
        summary: "Both actives pass individually and combined HQ below triggers.",
        assessor: "Mark Daly",
        lastUpdated: "2025-12-28",
      },
      {
        sectionId: "birds-mammals",
        riskLevel: "refinement-needed",
        summary: "Combined exposure assessment ongoing. Metconazole chronic risk to mammals needs refinement.",
        assessor: "Mark Daly",
        lastUpdated: "2025-12-28",
      },
      {
        sectionId: "nta",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "ntp",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "operator",
        riskLevel: "refinement-needed",
        summary: "Combined AOEL assessment: operator exposure at 82% of combined AOEL. Close to threshold.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-02-01",
      },
      {
        sectionId: "worker",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "resident-bystander",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "classification",
        riskLevel: "critical",
        summary: "Metconazole is Repr. 1B H360D - combination product classification may trigger withdrawal in some MS.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-15",
      },
      {
        sectionId: "gw-metabolites",
        riskLevel: "fail",
        summary: "Both active substances have relevant GW metabolites exceeding trigger. Major concern for Northern EU.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-18",
      },
      {
        sectionId: "validation",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "residue-studies",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "consumer-chronic",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "consumer-acute",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "combined-risk",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "field-trials",
        riskLevel: "pass",
        summary: "Strong efficacy data from 16 trials. Synergistic activity confirmed.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-09-15",
      },
      {
        sectionId: "bad",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "effectiveness",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "resistance",
        riskLevel: "not-started",
        summary: "",
      },
    ],
  },
  {
    id: "boscalid-500-sc",
    activeSubstance: "Boscalid",
    productName: "Boscalid 500 SC",
    type: "Fungicide",
    projectOwner: "Marie Walsh",
    countries: ["IE", "UK", "FR", "NL", "BE"],
    submissionType: "Art 33",
    status: "Assessment phase",
    targetSubmissionDate: "2026-03-01",
    dataResponsibility: "LS",
    euApprovalStatus: "Approved",
    euExpiryDate: "2028-07-31",
    assessments: [
      {
        sectionId: "aquatics",
        riskLevel: "pass",
        summary: "All Tier 1 TER values above triggers. Low aquatic toxicity profile.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2025-11-10",
      },
      {
        sectionId: "groundwater",
        riskLevel: "pass",
        summary: "Below 0.1 ug/L in all FOCUS scenarios.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2025-11-10",
      },
      {
        sectionId: "soil",
        riskLevel: "pass-with-mitigation",
        summary: "DT50 = 120 days. Accumulation plateau after 3 years acceptable but higher than typical.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2025-11-12",
      },
      {
        sectionId: "bees",
        riskLevel: "pass",
        summary: "No bee toxicity concerns. HQ well below triggers.",
        assessor: "Mark Daly",
        lastUpdated: "2025-10-20",
      },
      {
        sectionId: "birds-mammals",
        riskLevel: "pass",
        summary: "Low vertebrate toxicity. All TER values comfortably above triggers.",
        assessor: "Mark Daly",
        lastUpdated: "2025-10-20",
      },
      {
        sectionId: "nta",
        riskLevel: "pass",
        summary: "Low risk to non-target arthropods.",
        assessor: "Mark Daly",
        lastUpdated: "2025-10-22",
      },
      {
        sectionId: "ntp",
        riskLevel: "pass",
        summary: "No phytotoxicity observed in non-target plant studies.",
        assessor: "Mark Daly",
        lastUpdated: "2025-10-22",
      },
      {
        sectionId: "operator",
        riskLevel: "pass",
        summary: "Operator exposure 22% AOEL. Comfortable margin.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-11-01",
      },
      {
        sectionId: "worker",
        riskLevel: "pass",
        summary: "Worker exposure 15% AOEL with standard re-entry interval.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-11-01",
      },
      {
        sectionId: "resident-bystander",
        riskLevel: "pass",
        summary: "All exposure scenarios well below AOEL.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-11-02",
      },
      {
        sectionId: "classification",
        riskLevel: "pass",
        summary: "No classification triggers. Standard labelling.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-10-28",
      },
      {
        sectionId: "gw-metabolites",
        riskLevel: "pass",
        summary: "No relevant groundwater metabolites identified.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-10-28",
      },
      {
        sectionId: "validation",
        riskLevel: "pass",
        summary: "Method validated for all required matrices.",
        assessor: "Tom Brennan",
        lastUpdated: "2025-09-15",
      },
      {
        sectionId: "residue-studies",
        riskLevel: "pass",
        summary: "Full trial package available. Existing MRLs sufficient.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-10-10",
      },
      {
        sectionId: "consumer-chronic",
        riskLevel: "pass",
        summary: "Chronic intake 8% ADI.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-10-10",
      },
      {
        sectionId: "consumer-acute",
        riskLevel: "pass",
        summary: "Acute intake 18% ARfD.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-10-10",
      },
      {
        sectionId: "combined-risk",
        riskLevel: "pass",
        summary: "Hazard Index < 1. No combined risk concerns.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-10-12",
      },
      {
        sectionId: "field-trials",
        riskLevel: "pass",
        summary: "Excellent efficacy data package.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-08-30",
      },
      {
        sectionId: "bad",
        riskLevel: "pass",
        summary: "BAD completed and approved.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-09-01",
      },
      {
        sectionId: "effectiveness",
        riskLevel: "pass",
        summary: "Equivalent to reference product.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-09-01",
      },
      {
        sectionId: "resistance",
        riskLevel: "pass",
        summary: "FRAC Group 7. Standard resistance management in place.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-09-01",
      },
    ],
  },
  {
    id: "spinosad-480",
    activeSubstance: "Spinosad",
    productName: "Spinosad 480 SC",
    type: "Insecticide",
    projectOwner: "Declan Foley",
    countries: ["IE", "ES", "IT", "GR", "PT"],
    submissionType: "Renewal",
    status: "Early assessment",
    targetSubmissionDate: "2027-01-15",
    dataResponsibility: "LS+partner",
    euApprovalStatus: "Approved",
    euExpiryDate: "2028-01-31",
    assessments: [
      {
        sectionId: "aquatics",
        riskLevel: "pass-with-mitigation",
        summary: "Moderate aquatic toxicity. 10m buffer zone sufficient based on FOCUS Step 3.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-02-01",
      },
      {
        sectionId: "groundwater",
        riskLevel: "pass",
        summary: "Rapid degradation. No groundwater concerns.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-02-01",
      },
      {
        sectionId: "soil",
        riskLevel: "pass",
        summary: "Short DT50 (9 days). No soil organism concerns.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2026-02-02",
      },
      {
        sectionId: "bees",
        riskLevel: "critical",
        summary:
          "Highly toxic to bees. HQ oral exceeds trigger by 50x. Application restrictions required: no flowering crops, no bee-attractive weeds. Key regulatory concern.",
        assessor: "Mark Daly",
        lastUpdated: "2026-02-05",
      },
      {
        sectionId: "birds-mammals",
        riskLevel: "pass",
        summary: "Low vertebrate toxicity.",
        assessor: "Mark Daly",
        lastUpdated: "2026-01-28",
      },
      {
        sectionId: "nta",
        riskLevel: "fail",
        summary:
          "Broad-spectrum insecticide. Significant risk to beneficial arthropods. In-field risk unacceptable. Off-field risk requires substantial buffer.",
        assessor: "Mark Daly",
        lastUpdated: "2026-02-05",
      },
      {
        sectionId: "ntp",
        riskLevel: "pass",
        summary: "No herbicidal activity. No risk to non-target plants.",
        assessor: "Mark Daly",
        lastUpdated: "2026-01-28",
      },
      {
        sectionId: "operator",
        riskLevel: "pass",
        summary: "Low mammalian toxicity. Operator exposure well within limits.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-10",
      },
      {
        sectionId: "worker",
        riskLevel: "pass",
        summary: "Standard re-entry interval sufficient.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-10",
      },
      {
        sectionId: "resident-bystander",
        riskLevel: "pass",
        summary: "No concerns for residents or bystanders.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-10",
      },
      {
        sectionId: "classification",
        riskLevel: "pass",
        summary: "No human health classification triggers.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-08",
      },
      {
        sectionId: "gw-metabolites",
        riskLevel: "pass",
        summary: "No relevant metabolites.",
        assessor: "Lisa Chen",
        lastUpdated: "2026-01-08",
      },
      {
        sectionId: "validation",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "residue-studies",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "consumer-chronic",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "consumer-acute",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "combined-risk",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "field-trials",
        riskLevel: "pass",
        summary: "Good efficacy against target pests (thrips, lepidoptera).",
        assessor: "Conor Ryan",
        lastUpdated: "2025-12-01",
      },
      {
        sectionId: "bad",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "effectiveness",
        riskLevel: "not-started",
        summary: "",
      },
      {
        sectionId: "resistance",
        riskLevel: "refinement-needed",
        summary:
          "IRAC Group 5. Some field resistance reported in Western Flower Thrips. Resistance management plan under review.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-12-15",
      },
    ],
  },
  {
    id: "clomazone-360",
    activeSubstance: "Clomazone",
    productName: "Clomazone 360 CS",
    type: "Herbicide",
    projectOwner: "Niamh Kelly",
    countries: ["UK", "DE", "PL", "HU", "RO"],
    submissionType: "Art 33",
    status: "Dossier submitted - awaiting assessment",
    targetSubmissionDate: "2025-12-01",
    dataResponsibility: "LS",
    euApprovalStatus: "Approved",
    euExpiryDate: "2027-12-31",
    assessments: [
      {
        sectionId: "aquatics",
        riskLevel: "pass-with-mitigation",
        summary: "Requires 5m buffer zone. FOCUS Step 3 PEC below RAC for all aquatic organisms.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2025-09-15",
      },
      {
        sectionId: "groundwater",
        riskLevel: "pass",
        summary: "Below 0.1 ug/L in all scenarios. Capsule suspension formulation reduces leaching.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2025-09-15",
      },
      {
        sectionId: "soil",
        riskLevel: "pass",
        summary: "DT50 = 35 days. Acceptable soil organism TER values.",
        assessor: "Sarah O'Brien",
        lastUpdated: "2025-09-18",
      },
      {
        sectionId: "bees",
        riskLevel: "pass",
        summary: "No bee toxicity. Herbicide - not relevant for pollinators.",
        assessor: "Mark Daly",
        lastUpdated: "2025-09-10",
      },
      {
        sectionId: "birds-mammals",
        riskLevel: "pass",
        summary: "Low toxicity to vertebrates.",
        assessor: "Mark Daly",
        lastUpdated: "2025-09-10",
      },
      {
        sectionId: "nta",
        riskLevel: "pass",
        summary: "Low risk. Herbicide mechanism not relevant to arthropods.",
        assessor: "Mark Daly",
        lastUpdated: "2025-09-12",
      },
      {
        sectionId: "ntp",
        riskLevel: "refinement-needed",
        summary: "As a herbicide, volatilisation may affect neighbouring crops. Capsule suspension mitigates but vapour phase assessment needed.",
        assessor: "Mark Daly",
        lastUpdated: "2025-09-14",
      },
      {
        sectionId: "operator",
        riskLevel: "pass",
        summary: "Operator exposure 30% AOEL.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-08-20",
      },
      {
        sectionId: "worker",
        riskLevel: "pass",
        summary: "Not applicable - pre-emergence herbicide, no worker re-entry required.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-08-20",
      },
      {
        sectionId: "resident-bystander",
        riskLevel: "pass-with-mitigation",
        summary: "Vapour phase exposure model needed. With CS formulation and application timing restrictions, 18% AOEL.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-08-22",
      },
      {
        sectionId: "classification",
        riskLevel: "pass",
        summary: "No classification triggers.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-08-18",
      },
      {
        sectionId: "gw-metabolites",
        riskLevel: "pass",
        summary: "No relevant metabolites identified for clomazone.",
        assessor: "Lisa Chen",
        lastUpdated: "2025-08-18",
      },
      {
        sectionId: "validation",
        riskLevel: "pass",
        summary: "Analytical method validated.",
        assessor: "Tom Brennan",
        lastUpdated: "2025-07-15",
      },
      {
        sectionId: "residue-studies",
        riskLevel: "pass",
        summary: "Residue trials complete. Low residue profile in oilseed rape.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-08-01",
      },
      {
        sectionId: "consumer-chronic",
        riskLevel: "pass",
        summary: "5% ADI.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-08-01",
      },
      {
        sectionId: "consumer-acute",
        riskLevel: "pass",
        summary: "12% ARfD.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-08-01",
      },
      {
        sectionId: "combined-risk",
        riskLevel: "pass",
        summary: "No combined risk concerns.",
        assessor: "Anna Kowalski",
        lastUpdated: "2025-08-05",
      },
      {
        sectionId: "field-trials",
        riskLevel: "pass",
        summary: "Consistent weed control in oilseed rape and potatoes.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-07-20",
      },
      {
        sectionId: "bad",
        riskLevel: "pass",
        summary: "BAD completed.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-07-25",
      },
      {
        sectionId: "effectiveness",
        riskLevel: "pass",
        summary: "Equivalent to reference. CS formulation provides additional benefit.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-07-25",
      },
      {
        sectionId: "resistance",
        riskLevel: "pass",
        summary: "HRAC Group 13. Low resistance risk for current target weeds.",
        assessor: "Conor Ryan",
        lastUpdated: "2025-07-25",
      },
    ],
  },
  {
    id: "pyrac-200-ec",
    activeSubstance: "Pyraclostrobin",
    productName: "Pyraclostrobin 200 EC",
    type: "Fungicide",
    projectOwner: "Marie Walsh",
    countries: ["DE", "FR", "PL"],
    submissionType: "Renewal",
    status: "Pre-submission planning",
    targetSubmissionDate: "2027-03-01",
    dataResponsibility: "LS",
    euApprovalStatus: "Approved",
    euExpiryDate: "2027-10-31",
    assessments: [
      { sectionId: "aquatics", riskLevel: "fail", summary: "Very high aquatic toxicity. Tier 1 TER for fish = 0.5. FOCUS Step 4 required. Major data gap.", assessor: "Sarah O'Brien", lastUpdated: "2026-02-10" },
      { sectionId: "groundwater", riskLevel: "pass", summary: "Low mobility. No groundwater concerns.", assessor: "Sarah O'Brien", lastUpdated: "2026-02-10" },
      { sectionId: "soil", riskLevel: "pass-with-mitigation", summary: "DT50 = 65 days. Accumulation assessment shows plateau within acceptable range.", assessor: "Sarah O'Brien", lastUpdated: "2026-02-12" },
      { sectionId: "bees", riskLevel: "refinement-needed", summary: "Moderate bee toxicity. Higher tier assessment with refined exposure needed.", assessor: "Mark Daly", lastUpdated: "2026-02-08" },
      { sectionId: "birds-mammals", riskLevel: "pass", summary: "Acceptable risk to birds and mammals.", assessor: "Mark Daly", lastUpdated: "2026-02-08" },
      { sectionId: "nta", riskLevel: "refinement-needed", summary: "Broad-spectrum fungicide affects some beneficial arthropods. Off-field assessment ongoing.", assessor: "Mark Daly", lastUpdated: "2026-02-10" },
      { sectionId: "ntp", riskLevel: "pass", summary: "No risk to non-target plants.", assessor: "Mark Daly", lastUpdated: "2026-02-08" },
      { sectionId: "operator", riskLevel: "pass", summary: "Within AOEL limits.", assessor: "Lisa Chen", lastUpdated: "2026-01-20" },
      { sectionId: "worker", riskLevel: "pass", summary: "Standard re-entry sufficient.", assessor: "Lisa Chen", lastUpdated: "2026-01-20" },
      { sectionId: "resident-bystander", riskLevel: "pass", summary: "Below AOEL.", assessor: "Lisa Chen", lastUpdated: "2026-01-20" },
      { sectionId: "classification", riskLevel: "pass-with-mitigation", summary: "Skin Sens. 1 classification required on label.", assessor: "Lisa Chen", lastUpdated: "2026-01-18" },
      { sectionId: "gw-metabolites", riskLevel: "pass", summary: "No relevant metabolites.", assessor: "Lisa Chen", lastUpdated: "2026-01-18" },
      { sectionId: "validation", riskLevel: "not-started", summary: "" },
      { sectionId: "residue-studies", riskLevel: "not-started", summary: "" },
      { sectionId: "consumer-chronic", riskLevel: "not-started", summary: "" },
      { sectionId: "consumer-acute", riskLevel: "not-started", summary: "" },
      { sectionId: "combined-risk", riskLevel: "not-started", summary: "" },
      { sectionId: "field-trials", riskLevel: "not-started", summary: "" },
      { sectionId: "bad", riskLevel: "not-started", summary: "" },
      { sectionId: "effectiveness", riskLevel: "not-started", summary: "" },
      { sectionId: "resistance", riskLevel: "refinement-needed", summary: "FRAC Group 11 (QoI). Widespread resistance in some pathogens. Critical for registration strategy.", assessor: "Conor Ryan", lastUpdated: "2025-12-20" },
    ],
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
